ALTER TABLE Visa ADD COLUMN DateDebut TIMESTAMP;
ALTER TABLE Visa ADD COLUMN DateExpiration TIMESTAMP;

ALTER TABLE CarteResident ADD COLUMN DateDebut TIMESTAMP;
ALTER TABLE CarteResident ADD COLUMN DateExpiration TIMESTAMP;
